 -------- Drop if necessary  --------
DROP TABLE SAILW0800V.GP_EVENTS_OF_INTEREST;


 -------- Create table --------
CREATE TABLE SAILW0800V.GP_EVENTS_OF_INTEREST AS (
	SELECT ch.ALF_PE, ch.ENTER_COHORT, ch.EXIT_COHORT, gp.EVENT_CD, gp.EVENT_VAL, gp.EVENT_DT, readcodes.READ_CODE, readcodes.READ_TYPE, readcodes."pre2010" AS pre_2010, readcodes."StudyPeriod20102019" AS study_period  FROM SAILW0800V.COHORT_ENTRY ch
LEFT JOIN (
	SELECT *
	FROM SAIL0800V.WLGP_GP_EVENT_CLEANSED_20220101) AS gp
	ON ch.ALF_PE = gp.ALF_PE
	
RIGHT JOIN (
	SELECT * FROM SAILW0800V.IMPORTED_CVD_READCODES codes) as readcodes
		ON readcodes.READ_CODE = gp.EVENT_CD
		WHERE gp.ALF_STS_CD IN (1, 39)
		AND gp.ALF_PE IS NOT NULL
		AND EVENT_DT BETWEEN ENTER_COHORT AND EXIT_COHORT
			AND NOT readcodes."StudyPeriod20102019" = 0) WITH NO DATA ;
		

	
 -------- insert CVD readcodes  -------- 
INSERT INTO SAILW0800V.GP_EVENTS_OF_INTEREST(
	SELECT ch.ALF_PE, ch.ENTER_COHORT, ch.EXIT_COHORT, gp.EVENT_CD, gp.EVENT_VAL, gp.EVENT_DT, readcodes.READ_CODE, readcodes.READ_TYPE, readcodes."pre2010" AS pre_2010, readcodes."StudyPeriod20102019" AS study_period  FROM SAILW0800V.COHORT_ENTRY ch
LEFT JOIN (
	SELECT *
	FROM SAIL0800V.WLGP_GP_EVENT_CLEANSED_20220101) AS gp
	ON ch.ALF_PE = gp.ALF_PE
	
RIGHT JOIN (
	SELECT * FROM SAILW0800V.IMPORTED_CVD_READCODES codes) as readcodes
		ON readcodes.READ_CODE = gp.EVENT_CD
		WHERE gp.ALF_STS_CD IN (1, 39)
		AND gp.ALF_PE IS NOT NULL
		AND EVENT_DT BETWEEN ENTER_COHORT AND EXIT_COHORT
			AND NOT readcodes."StudyPeriod20102019" = 0);
			
		
---- insert CVD DRUGS
INSERT INTO SAILW0800V.GP_EVENTS_OF_INTEREST(
	SELECT ch.ALF_PE, ch.ENTER_COHORT, ch.EXIT_COHORT, gp.EVENT_CD, gp.EVENT_VAL, gp.EVENT_DT, readcodes.READ_CODE, readcodes.READ_TYPE, readcodes."PRE2010" AS pre_2010, readcodes."STUDYPERIOD20102019" AS study_period FROM SAILW0800V.COHORT_ENTRY ch
LEFT JOIN (
	SELECT *
	FROM SAIL0800V.WLGP_GP_EVENT_CLEANSED_20220101) AS gp
	ON ch.ALF_PE = gp.ALF_PE
	
RIGHT JOIN (
	SELECT * FROM SAILW0800V.CVD_DRUGS codes) as readcodes
		ON readcodes.READ_CODE = gp.EVENT_CD
		WHERE gp.ALF_STS_CD IN (1, 39)
		AND gp.ALF_PE IS NOT NULL
		AND EVENT_DT BETWEEN ENTER_COHORT AND EXIT_COHORT
			AND NOT readcodes."STUDYPERIOD20102019" = 0) ;

	
			
 
---- insert MH codes
INSERT INTO SAILW0800V.GP_EVENTS_OF_INTEREST(
	SELECT ch.ALF_PE, ch.ENTER_COHORT, ch.EXIT_COHORT, gp.EVENT_CD, gp.EVENT_VAL, gp.EVENT_DT, readcodes.READ_CODE, readcodes.READ_TYPE, readcodes."pre2010" AS pre_2010, readcodes."StudyPeriod20102019" AS study_period  FROM SAILW0800V.COHORT_ENTRY ch
LEFT JOIN (
	SELECT *
	FROM SAIL0800V.WLGP_GP_EVENT_CLEANSED_20220101) AS gp
	ON ch.ALF_PE = gp.ALF_PE
	
RIGHT JOIN (
	SELECT * FROM SAILW0800V.IMPORTED_MH_READCODES codes) as readcodes
		ON readcodes.READ_CODE = gp.EVENT_CD
		WHERE gp.ALF_STS_CD IN (1, 39)
		AND gp.ALF_PE IS NOT NULL
		AND EVENT_DT BETWEEN ENTER_COHORT AND EXIT_COHORT
			AND NOT readcodes."StudyPeriod20102019" = 0);
			

			

---- insert CVD RISK ASSESSMENT
INSERT INTO SAILW0800V.GP_EVENTS_OF_INTEREST(
	SELECT ch.ALF_PE, ch.ENTER_COHORT, ch.EXIT_COHORT, gp.EVENT_CD, gp.EVENT_VAL, gp.EVENT_DT, readcodes.READ_CODE, readcodes.READ_TYPE, readcodes.PRE_2010 , readcodes.STUDY_PERIOD  FROM SAILW0800V.COHORT_ENTRY ch
LEFT JOIN (
	SELECT *
	FROM SAIL0800V.WLGP_GP_EVENT_CLEANSED_20220101) AS gp
	ON ch.ALF_PE = gp.ALF_PE
	
RIGHT JOIN (
	SELECT * FROM SAILW0800V.CVD_RISK_ASSESS_CODES codes) as readcodes
		ON readcodes.READ_CODE = gp.EVENT_CD
		WHERE gp.ALF_STS_CD IN (1, 39)
		AND gp.ALF_PE IS NOT NULL
		AND EVENT_DT BETWEEN ENTER_COHORT AND EXIT_COHORT
			AND NOT readcodes."STUDY_PERIOD" = 0)		;
			
SELECT * FROM SAILW0800V.GP_EVENTS_OF_INTEREST;

---- insert Anxiety Alternative Diag		
INSERT INTO SAILW0800V.GP_EVENTS_OF_INTEREST (SELECT ch.ALF_PE, 
	ch.ENTER_COHORT, 
	ch.EXIT_COHORT, 
	'alt.anx' AS EVENT_CD, 
	NULL AS EVENT_VAL,
	aad.EVENT_DT,
	'alt.anx' AS READ_CODE,
	'anxiety_alt_diag' AS READ_TYPE, 
	-1 AS PRE_2010,
	1 AS STUDY_PERIOD
		FROM SAILW0800V.COHORT_ENTRY ch
		LEFT JOIN (SELECT ALF_PE, EARLIEST_DATE AS EVENT_DT FROM SAILW0800V.MHTable_Alternative_Anxiety_Diagnosis) AS aad 
		ON ch.ALF_PE = aad.ALF_PE
		WHERE aad.EVENT_DT BETWEEN ch.ENTER_COHORT AND ch.EXIT_COHORT);
	

---- insert Depression Alternative Diag	
INSERT INTO SAILW0800V.GP_EVENTS_OF_INTEREST (SELECT ch.ALF_PE, 
	ch.ENTER_COHORT, 
	ch.EXIT_COHORT, 
	'alt.dep' AS EVENT_CD, 
	NULL AS EVENT_VAL,
	aad.EVENT_DT,
	'alt.dep' AS READ_CODE,
	'depression_alt_diag' AS READ_TYPE, 
	-1 AS PRE_2010,
	1 AS STUDY_PERIOD
		FROM SAILW0800V.COHORT_ENTRY ch
		LEFT JOIN (SELECT ALF_PE, EARLIEST_DATE AS EVENT_DT FROM SAILW0800V.MHTable_Alternative_Diagnosis) AS aad 
		ON ch.ALF_PE = aad.ALF_PE
		WHERE aad.EVENT_DT BETWEEN ch.ENTER_COHORT AND ch.EXIT_COHORT);