
----------------------------------------------------
DROP TABLE SAILW0800V.COHORT_BASE_TABLE_HISTORY;
	
CREATE TABLE SAILW0800V.COHORT_BASE_TABLE_HISTORY (
	ALF_PE					BIGINT,
	READ_CODE				VARCHAR(10),
	READ_TYPE				VARCHAR(30),
	EVENT_DT				DATE,
	EVENT_VAL				DECIMAL(31,8),
	HOSP_GP					VARCHAR(1));




-------------------------------------------------------
-------------------------------------------------------
--------  Insert GP codes First

 -------- insert CVD readcodes  -------- 
INSERT INTO SAILW0800V.COHORT_BASE_TABLE_HISTORY (
SELECT ch.ALF_PE, gp.EVENT_CD, readcodes.READ_TYPE, gp.EVENT_DT, gp.EVENT_VAL, 1 AS HOSP_GP
FROM SAILW0800V.COHORT_ENTRY ch
LEFT JOIN (
	SELECT *
	FROM SAIL0800V.WLGP_GP_EVENT_CLEANSED_20220101) AS gp
	ON ch.ALF_PE = gp.ALF_PE	
RIGHT JOIN (
	SELECT * FROM SAILW0800V.IMPORTED_CVD_READCODES codes) as readcodes
		ON readcodes.READ_CODE = gp.EVENT_CD
		WHERE gp.ALF_STS_CD IN (1, 39)
		AND gp.ALF_PE IS NOT NULL
		AND EVENT_DT < ENTER_COHORT
		AND NOT readcodes."pre2010" = 0);
		
		

			
		
---- insert CVD DRUGS
INSERT INTO SAILW0800V.COHORT_BASE_TABLE_HISTORY (
SELECT ch.ALF_PE, gp.EVENT_CD, readcodes.READ_TYPE, gp.EVENT_DT, gp.EVENT_VAL, 1 AS HOSP_GP
FROM SAILW0800V.COHORT_ENTRY ch
LEFT JOIN (
	SELECT *
	FROM SAIL0800V.WLGP_GP_EVENT_CLEANSED_20220101) AS gp
	ON ch.ALF_PE = gp.ALF_PE
	
RIGHT JOIN (
	SELECT * FROM SAILW0800V.CVD_DRUGS codes) as readcodes
		ON readcodes.READ_CODE = gp.EVENT_CD
		WHERE gp.ALF_STS_CD IN (1, 39)
		AND gp.ALF_PE IS NOT NULL
		AND EVENT_DT < ENTER_COHORT
		AND NOT readcodes."PRE2010" = 0) ;



---- insert CVD RISK ASSESSMENT
INSERT INTO SAILW0800V.COHORT_BASE_TABLE_HISTORY (
SELECT ch.ALF_PE, gp.EVENT_CD, readcodes.READ_TYPE, gp.EVENT_DT, gp.EVENT_VAL, 1 AS HOSP_GP
FROM SAILW0800V.COHORT_ENTRY ch
LEFT JOIN (
	SELECT *
	FROM SAIL0800V.WLGP_GP_EVENT_CLEANSED_20220101) AS gp
	ON ch.ALF_PE = gp.ALF_PE
	
RIGHT JOIN (
	SELECT * FROM SAILW0800V.CVD_RISK_ASSESS_CODES codes) as readcodes
		ON readcodes.READ_CODE = gp.EVENT_CD
		WHERE gp.ALF_STS_CD IN (1, 39)
		AND gp.ALF_PE IS NOT NULL
		AND EVENT_DT < ENTER_COHORT
			AND NOT readcodes."STUDY_PERIOD" = 0);		
						
 
---- insert MH codes
INSERT INTO SAILW0800V.COHORT_BASE_TABLE_HISTORY (
SELECT ch.ALF_PE, gp.EVENT_CD, readcodes.READ_TYPE, gp.EVENT_DT, gp.EVENT_VAL, 1 AS HOSP_GP
FROM SAILW0800V.COHORT_ENTRY ch
LEFT JOIN (
	SELECT *
	FROM SAIL0800V.WLGP_GP_EVENT_CLEANSED_20220101) AS gp
	ON ch.ALF_PE = gp.ALF_PE
	
RIGHT JOIN (
	SELECT * FROM SAILW0800V.IMPORTED_MH_READCODES codes) as readcodes
		ON readcodes.READ_CODE = gp.EVENT_CD
		WHERE gp.ALF_STS_CD IN (1, 39)
		AND gp.ALF_PE IS NOT NULL
		AND EVENT_DT < ENTER_COHORT
		AND NOT readcodes."pre2010" = 0);
			

			
	
			


		
------ Insert Alternative Diagnoses for Anxiety and Depression
INSERT INTO SAILW0800V.COHORT_BASE_TABLE_HISTORY (
SELECT DISTINCT ch.ALF_PE, 'anx.alt' AS READ_CODE, 'anxiety_alt_diag' AS READ_TYPE, aad.EARLIEST_DATE, NULL AS EVENT_VAL, 1 AS HOSP_GP
FROM SAILW0800V.COHORT_ENTRY ch
		LEFT JOIN (SELECT ALF_PE, EARLIEST_DATE FROM SAILW0800V.MHTable_Alternative_Diagnosis WHERE NOT EARLIEST_DATE IS NULL) AS aad 
		ON ch.ALF_PE = aad.ALF_PE
		WHERE aad.EARLIEST_DATE < ch.ENTER_COHORT)	;	
	


	
INSERT INTO SAILW0800V.COHORT_BASE_TABLE_HISTORY (
SELECT DISTINCT ch.ALF_PE, 'anx.alt' AS READ_CODE, 'depression_alt_diag' AS READ_TYPE, aad.EARLIEST_DATE, NULL AS EVENT_VAL, 1 AS HOSP_GP
FROM SAILW0800V.COHORT_ENTRY ch
		LEFT JOIN (SELECT ALF_PE, EARLIEST_DATE FROM SAILW0800V.MHTable_Alternative_Diagnosis WHERE NOT EARLIEST_DATE IS NULL) AS aad 
		ON ch.ALF_PE = aad.ALF_PE
		WHERE aad.EARLIEST_DATE < ch.ENTER_COHORT	);

		
	
---------------------------------------------------
---------------------------------------------------
--------  Insert PEDW


		
INSERT INTO SAILW0800V.COHORT_BASE_TABLE_HISTORY (
SELECT ch.ALF_PE, pedw.DIAG_CD_1234, readcodes.ICD_TYPE, pedw.START_DATE, 0 AS EVENT_VAL, 2 AS HOSP_GP
FROM SAILW0800V.COHORT_ENTRY ch	
LEFT JOIN (
	SELECT *
	FROM SAIL0800V.PEDW_SINGLE_DIAG_20220801 psd ) AS pedw
	ON ch.ALF_PE = pedw.ALF_PE

	RIGHT JOIN (SELECT * FROM SAILW0800V.IMPORTED_CVD_ICDCODES) as readcodes
			ON pedw.DIAG_CD_1234  = readcodes.DIAG_CD_4
	WHERE pedw.START_DATE < ch.ENTER_COHORT
		AND NOT readcodes."pre2010" = 0) ;		



--------  Insert PEDW OPCS codes 
INSERT INTO SAILW0800V.COHORT_BASE_TABLE_HISTORY (
SELECT ch.ALF_PE, pedw.DIAG_CD_1234, readcodes.OPCS_TYPE, pedw.START_DATE, 0 AS EVENT_VAL, 2 AS HOSP_GP
FROM SAILW0800V.COHORT_ENTRY ch	
LEFT JOIN (
SELECT * FROM SAIL0800V.PEDW_SINGLE_DIAG_20220801 pedw ) AS pedw
	ON ch.ALF_PE = pedw.ALF_PE

	RIGHT JOIN (SELECT * FROM SAILW0800V.IMPORTED_CVD_PROCEDURECODES) as readcodes
			ON pedw.DIAG_CD_1234  = readcodes.CODE_WITHOUT_DECIMAL
	WHERE pedw.START_DATE < ch.ENTER_COHORT
		AND NOT readcodes."pre2010" = 0) ;


